#!/bin/bash
set -e

echo "=== Building Spresense UAC2 192kHz/24bit DAC (Rev85: DMA playback + ASMP + DCD ISOC patch) ==="
TOOLS_ROOT="${SPRESENSE_TOOLS:-$HOME/spresense-tools}"
export PATH="$TOOLS_ROOT/gcc-arm-none-eabi-9-2020-q2-update/bin:$HOME/spresenseenv/usr/bin:/usr/bin:/bin"

SPRESENSE="${SPRESENSE:-$HOME/spresense}"
SDK=$SPRESENSE/sdk
NUTTX=$SPRESENSE/nuttx
DOTCONFIG=$NUTTX/.config
APP_LINK=$SDK/apps/examples/uac2_dac
APP_SRC="$(cd "$(dirname "$0")" && pwd)"

# Board serial port: explicit arg or UAC2_FLASH_PORT (fail fast, before build)
PORT="${1:-${UAC2_FLASH_PORT:-}}"
if [ -z "$PORT" ]; then
    echo "[ERROR] No serial port given. Usage: $0 <serial-port>"
    echo "  Windows: Device Manager -> Ports (COM & LPT)"
    echo "  Linux:   ls /dev/ttyUSB*"
    echo "  Or set the UAC2_FLASH_PORT environment variable."
    exit 1
fi

# 1. Ensure symlink apps/examples/uac2_dac -> spresense_uac2_dac
if [ ! -e "$APP_LINK" ]; then
    echo "[LINK] Creating symlink $APP_LINK -> $APP_SRC"
    ln -s "$APP_SRC" "$APP_LINK"
else
    echo "[LINK] OK: $APP_LINK exists ($(readlink $APP_LINK))"
fi

cd $SDK

# 1b. Regenerate apps/examples/Kconfig so the uac2_dac symlink's Kconfig
#     is visible to kconfig (autogenerated file, otherwise the symbol is
#     unknown and olddefconfig silently drops CONFIG_EXAMPLES_UAC2_DAC).
#     NOTE: must run inside apps/examples (script uses $PWD); never run it
#     from $SDK (that would overwrite the SDK-level Kconfig).
echo "[LINK] Regenerating apps/examples/Kconfig..."
(cd apps/examples && bash ../tools/mkkconfig.sh -m "Examples")
grep -q "uac2_dac/Kconfig" apps/examples/Kconfig && \
  echo "[LINK] OK: uac2_dac in examples/Kconfig" || \
  { echo "[ERROR] uac2_dac missing from apps/examples/Kconfig"; exit 1; }

# 1c. Apply the Phase-2 DCD ISOC patch to the SDK's cxd56_usbdev.c.
#     Stock DCD exposes only BULK/INT EPs, so ISOC allocation fails and
#     no audio streams. The patch (recovered from project history,
#     pre-pruning cxd56_ref) converts EP1/EP2 to ISOC, latches EP CSRs,
#     and uses SNAK-instead-of-STALL on disable (fixes HW Alt>0 STALL).
#     Idempotent: `patch -N` skips when already applied.
echo "[PATCH] Applying DCD ISOC patch..."
patch -d "$NUTTX" -p1 -N --silent < "$APP_SRC/patches/cxd56_usbdev.isoc.patch" 2>/dev/null && \
  echo "[PATCH] Applied" || echo "[PATCH] Already applied (skipped)"
grep -q "Isochronous (UAC2 Audio OUT)" "$NUTTX/arch/arm/src/cxd56xx/cxd56_usbdev.c" && \
  echo "[PATCH] OK: ISOC EPs present" || \
  { echo "[ERROR] DCD ISOC patch missing after apply"; exit 1; }

# 2. Ensure required Kconfig options in nuttx/.config
#    USB device controller + USBDEV core for enumeration; ISOC EPs,
#    DMA playback, ASMP telemetry are provided by the DCD patch + app.
if [ ! -f "$DOTCONFIG" ]; then
    echo "[ERROR] $DOTCONFIG not found. Run tools/config.py first (e.g. ./tools/config.py default)."
    exit 1
fi

ensure_config() {
    key="$1"
    val="$2"
    if ! grep -q "^${key}=" "$DOTCONFIG" 2>/dev/null; then
        echo "[CONFIG] Adding ${key}=${val}"
        echo "${key}=${val}" >> "$DOTCONFIG"
    else
        echo "[CONFIG] OK: ${key} already set ($(grep "^${key}=" "$DOTCONFIG"))"
    fi
}

enable_config() {
    key="$1"
    if grep -q "^# ${key} is not set" "$DOTCONFIG" 2>/dev/null; then
        echo "[CONFIG] Enabling ${key} (was not set)"
        sed -i "s/^# ${key} is not set/${key}=y/" "$DOTCONFIG"
    fi
    ensure_config "$key" "y"
}

disable_config() {
    key="$1"
    if grep -q "^${key}=" "$DOTCONFIG" 2>/dev/null; then
        echo "[CONFIG] Disabling ${key}"
        sed -i "s/^${key}=.*/# ${key} is not set/" "$DOTCONFIG"
    fi
}

# 1. Disable MIDI Synth & Multicore to free SRAM
echo "[CONFIG] Disabling HexaMIDI (CONFIG_EXAMPLES_SYNTH) for dedicated UAC2 DAC..."
disable_config "CONFIG_EXAMPLES_SYNTH"
disable_config "CONFIG_EXAMPLES_SYNTH_MULTICORE"

# 2. Set boot entrypoint to uac2_dac_main
echo "[CONFIG] Setting boot entrypoint to uac2_dac_main..."
sed -i 's/CONFIG_INIT_ENTRYPOINT=.*/CONFIG_INIT_ENTRYPOINT="uac2_dac_main"/' "$DOTCONFIG"
sed -i 's/CONFIG_INIT_ENTRYNAME=.*/CONFIG_INIT_ENTRYNAME="uac2_dac_main"/' "$DOTCONFIG"
sed -i 's/CONFIG_INIT_STACKSIZE=.*/CONFIG_INIT_STACKSIZE=8192/' "$DOTCONFIG"

# 3. Enable USB device & UAC2 DAC
enable_config "CONFIG_CXD56_USBDEV"
enable_config "CONFIG_USBDEV"
ensure_config "CONFIG_USBDEV_DMA" "y"
ensure_config "CONFIG_USBDEV_DUALSPEED" "y"
ensure_config "CONFIG_USBDEV_SELFPOWERED" "y"
ensure_config "CONFIG_USBDEV_MAXPOWER" "100"
enable_config "CONFIG_EXAMPLES_UAC2_DAC"
ensure_config "CONFIG_EXAMPLES_UAC2_DAC_PROGNAME" "\"uac2_dac\""
ensure_config "CONFIG_EXAMPLES_UAC2_DAC_PRIORITY" "100"
ensure_config "CONFIG_EXAMPLES_UAC2_DAC_STACKSIZE" "8192"

# 4b. ASMP sub-core formatter (phase 1): boot SubCore 1 monw worker.
#     Set UAC2_ASMP=0 to skip (local formatting fallback).
if [ "${UAC2_ASMP:-1}" = "0" ]; then
  echo "[CONFIG] ASMP sub-core disabled (UAC2_ASMP=0)"
  disable_config "CONFIG_EXAMPLES_UAC2_DAC_ASMP"
else
  enable_config "CONFIG_EXAMPLES_UAC2_DAC_ASMP"
  # Force (not just ensure): loader needs the room for the worker ELF.
  sed -i 's/^CONFIG_ASMP_MEMSIZE=.*/CONFIG_ASMP_MEMSIZE=0xc0000/' "$DOTCONFIG"
  ensure_config "CONFIG_ASMP_MEMSIZE" "0xc0000"
fi

# 4. Enable Audio Subsystem (CXD5247 /dev/pcm0 for Phase 3 playback)
enable_config "CONFIG_AUDIO"
enable_config "CONFIG_AUDIO_CXD56"
# Board audio driver (cxd56_audio_* board APIs: set_clkmode, power, etc.)
# NOTE: CXD56_AUDIO is only visible when SPECIFIC_DRIVERS=y (board drivers
# Kconfig is gated on it), so enable that first.
enable_config "CONFIG_SPECIFIC_DRIVERS"
enable_config "CONFIG_CXD56_AUDIO"

# 5. True multicore (SMP): keep NuttX on 2 CPUs so telemetry (MON thread)
#    runs on the sub-core while the audio pump stays on the main core.
#    Requires `tools/config.py default feature/smp` as the base config.
#    DEFAULT IS SINGLE-CORE (UAC2_SMP=0): the CXD56 USB/audio driver stack
#    wedges deterministically under SMP (verified A/B: SMP dies at pump
#    start under ISO traffic, UP streams clean for 60s+). The MON thread
#    still isolates all UART by priority. Set UAC2_SMP=1 only to experiment.
if [ "${UAC2_SMP:-0}" = "0" ]; then
  echo "[CONFIG] Single-core build requested (UAC2_SMP=0): disabling SMP..."
  disable_config "CONFIG_SMP"
  disable_config "CONFIG_SYSTEM_SYSTEM"
  disable_config "CONFIG_SYSTEM_TASKSET"
else
  enable_config "CONFIG_SMP"
  ensure_config "CONFIG_SMP_NCPUS" "2"
  enable_config "CONFIG_SYSTEM_SYSTEM"
  enable_config "CONFIG_SYSTEM_TASKSET"
fi

# Ensure clean rebuild of app objects
rm -f "$APP_SRC/.built" "$APP_SRC"/src/*.o "$SDK/apps/libapps.a" "$NUTTX/staging/libapps.a"


# Refresh auto-generated Kconfig (picks up uac2_dac/Kconfig via symlink) and
# resolve dependencies without prompting.
echo "[CONFIG] Running olddefconfig..."
make olddefconfig

# 3. Build nuttx.spk
echo "[BUILD] Compiling nuttx and apps..."
make -j8

# nuttx.spk is generated in sdk/ (Spresense SDK layout)
if [ ! -f nuttx.spk ]; then
    echo "[ERROR] nuttx.spk not found after build."
    exit 1
fi

# Remove path-mangled object files (e.g. uac2_desc.c.home.user.proj.o) that
# the NuttX apps build drops into src/ — filenames embed the absolute path.
rm -f "$APP_SRC"/src/*.o

# 4. Flash (port validated at startup)
echo "[FLASH] Flashing to Spresense on $PORT..."
./tools/flash.sh -c "$PORT" -b 115200 nuttx.spk

echo "=== Build and Flash Complete! ==="
echo "1. Connect 115200bps serial terminal (spresense main console)."
echo "2. Run:  nsh> uac2_dac"
echo "3. Connect Spresense USB (device port) to PC."
echo "4. On PC run:  python3 tools/usb_probe.py   (or check Sound settings)"
echo "   Expect: 'Spresense 192kHz/24bit Audio' with 192000 Hz, 2ch, 24-bit."

